name: Build Native

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  native-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1.0.2
    - name: Restore
      run: nuget restore src/BehaviorsSDKNative/BehaviorsSDKNative.sln
    - uses: microsoft/setup-msbuild@v1.0.1
    - name: Build
      run: msbuild src/BehaviorsSDKNative/BehaviorsSDKNative.sln /p:Configuration=Release